# Generated by Django 4.2.15 on 2024-09-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('name', models.CharField(max_length=120)),
                ('cooking_time', models.IntegerField()),
                ('ingredients', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=12)),
            ],
        ),
    ]
